spring.application.name=cloud-app-catalog
server.port=8080

# Supabase (POOLER - IPv4 compatible)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.uypaizblywqnrbzawyrw
spring.datasource.password=Gowtham@2940

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false